/* SKU CoE ITE - ParkSooYoung */
/* Grade 1 , Semester 1 , Report 2 : Big Special Character Name */

#include <stdio.h>

int main(void)
{
	char name;

	printf("사용하고자 하는 문자를 입력하세요 : ");
	scanf("%c", &name);

	printf("                                                                                                                                                                                                                           \n");
	printf("%c                            %c %c                         %c%c%c%c%c%c%c%c%c%c%c%c%c%c%c                       %c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c                %c                                                \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("%c                            %c %c                        %c%c%c%c%c       %c%c%c%c%c                     %c%c%c%c%c            %c%c%c%c%c               %c                                                               \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("%c                            %c %c                       %c%c%c%c%c         %c%c%c%c%c                   %c%c%c%c%c              %c%c%c%c%c              %c                                                               \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("%c                            %c %c                      %c%c%c%c%c           %c%c%c%c%c                 %c%c%c%c%c                %c%c%c%c%c             %c                                                               \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("%c                            %c %c                     %c%c%c%c%c             %c%c%c%c%c               %c%c%c%c%c                  %c%c%c%c%c            %c                                                               \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("%c                            %c %c                    %c%c%c%c%c               %c%c%c%c%c             %c%c%c%c%c                    %c%c%c%c%c           %c                                                               \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("%c                            %c %c                   %c%c%c%c%c                 %c%c%c%c%c           %c%c%c%c%c                      %c%c%c%c%c %c%c%c%c%c%c%c%c%c%c                                                      \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c %c%c%c%c%c%c%c%c%c%c         %c%c%c%c%c                   %c%c%c%c%c         %c%c%c%c%c                        %c%c%c%c%c         %c                          \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("%c                            %c %c                 %c%c%c%c%c                     %c%c%c%c%c        %c%c%c%c%c                        %c%c%c%c%c         %c                                                               \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("%c                            %c %c                %c%c%c%c%c                       %c%c%c%c%c        %c%c%c%c%c                      %c%c%c%c%c %c%c%c%c%c%c%c%c%c%c                                                      \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("%c                            %c %c               %c%c%c%c%c                         %c%c%c%c%c        %c%c%c%c%c                    %c%c%c%c%c           %c                                                               \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("%c                            %c %c              %c%c%c%c%c                           %c%c%c%c%c        %c%c%c%c%c                  %c%c%c%c%c            %c                                                               \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("%c                            %c %c             %c%c%c%c%c                             %c%c%c%c%c        %c%c%c%c%c                %c%c%c%c%c             %c                                                               \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("%c                            %c %c            %c%c%c%c%c                               %c%c%c%c%c        %c%c%c%c%c              %c%c%c%c%c              %c                                                               \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("%c                            %c %c           %c%c%c%c%c                                 %c%c%c%c%c        %c%c%c%c%c            %c%c%c%c%c               %c                                                               \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c %c          %c%c%c%c%c                                   %c%c%c%c%c        %c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c                %c                         \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("                                                                                                                                                                                                                           \n");
	printf(" %c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c           %c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c                %c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("                              %c                                 %c                                     %c%c%c%c%c            %c%c%c%c%c                                                                                   \n", name, name, name, name, name, name, name, name, name, name, name, name);
	printf("                              %c                                 %c                                    %c%c%c%c%c              %c%c%c%c%c                                                                                  \n", name, name, name, name, name, name, name, name, name, name, name, name);
	printf("                              %c                                 %c                                   %c%c%c%c%c                %c%c%c%c%c                                                                                 \n", name, name, name, name, name, name, name, name, name, name, name, name);
	printf("                              %c                                 %c                                  %c%c%c%c%c                  %c%c%c%c%c                                                                                \n", name, name, name, name, name, name, name, name, name, name, name, name);
	printf("                              %c                                 %c                                 %c%c%c%c%c                    %c%c%c%c%c                                                                               \n", name, name, name, name, name, name, name, name, name, name, name, name);
	printf("                              %c                                 %c                                %c%c%c%c%c                      %c%c%c%c%c                                                                              \n", name, name, name, name, name, name, name, name, name, name, name, name);
	printf("                              %c                                 %c                                %c%c%c%c%c                      %c%c%c%c%c                                                                              \n", name, name, name, name, name, name, name, name, name, name, name, name);
	printf("                              %c                                 %c                                 %c%c%c%c%c                    %c%c%c%c%c                                                                               \n", name, name, name, name, name, name, name, name, name, name, name, name);
	printf("                              %c                                 %c                                  %c%c%c%c%c                  %c%c%c%c%c                                                                                \n", name, name, name, name, name, name, name, name, name, name, name, name);
	printf("                              %c                                 %c                                   %c%c%c%c%c                %c%c%c%c%c                                                                                 \n", name, name, name, name, name, name, name, name, name, name, name, name);
	printf("                              %c                                 %c                                    %c%c%c%c%c              %c%c%c%c%c                                                                                  \n", name, name, name, name, name, name, name, name, name, name, name, name);
	printf("                              %c                                 %c                                     %c%c%c%c%c            %c%c%c%c%c                                                                                   \n", name, name, name, name, name, name, name, name, name, name, name, name);
	printf("                              %c                                 %c                                      %c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c%c                                                                          \n", name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name);
	printf("                                                                                                                                                                                                                           \n");

	return 0;
}
